
project_id = "jxvrpnjluuvoggxonfll"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"

[edge_functions]
enabled = true
port = 54325

[functions.chat-ai]
verify_jwt = true

[functions.process-document]
verify_jwt = true

[functions.send-invitation]
verify_jwt = true

[db]
port = 54322

[studio]
enabled = true
port = 54323

[storage]
enabled = true
port = 54324
