// Cerebro · Growth Agent
//
// Generates 5 faceless slideshow concepts for the upcoming week
// (Mon-Fri) following docs/MARKETING_FACELESS_STRATEGY.md.
//
// Each slideshow includes: hook, 3-5 body slides, CTA with UTM.
// Output: docs/growth/YYYY-MM-DD-week.md committed to repo.
//
// Required env vars (GitHub Actions secrets):
//   - ANTHROPIC_API_KEY

import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname } from 'node:path'

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY
if (!ANTHROPIC_API_KEY) {
  console.error('Missing ANTHROPIC_API_KEY')
  process.exit(1)
}

const today = new Date().toISOString().slice(0, 10)
const monday = (() => {
  const d = new Date()
  const dow = d.getDay() // 0=Sun
  const offset = dow === 0 ? 1 : (1 - dow + 7) % 7
  d.setDate(d.getDate() + offset)
  return d.toISOString().slice(0, 10)
})()

const SYSTEM_PROMPT = `Eres senior growth marketer especializado en B2B SaaS LATAM y faceless content.
Cerebro es la capa de contexto operacional para humanos y agentes IA. ICP: empresas tech-forward 50-200 personas en LATAM/España hispana, Heads de Ops/CS/People/AI.

Generas 5 slideshows faceless de 5-7 slides cada uno para postear en TikTok/LinkedIn/Reels.
Estructura: Hook (3 seg) → Body (3-5 slides con texto + descripción visual) → CTA con UTM.

Tono: directo, sin jerga, números concretos. Siempre alguien específico debe sentir el dolor.

Devuelves JSON array. Cada item:
{
  "day": "lunes" | "martes" | "miercoles" | "jueves" | "viernes",
  "topic": string (1 línea),
  "audience": string (a quien le habla),
  "hook": string (3-5 palabras impactantes para slide 1),
  "body": [{"slide": 2, "text": string, "visual_hint": string}, ...],
  "cta": {"text": string, "url": string with utm params},
  "format_priority": "tiktok" | "linkedin" | "reels"
}`

const userPrompt = `Genera el calendario de slideshows para la semana del ${monday}.

Mezcla los 4 ángulos del docs/MARKETING_FACELESS_STRATEGY.md:
1. Onboarding: el dolor (lunes - el más fuerte)
2. Operaciones: decisiones repetidas
3. Agentes IA + MCP server (wedge YC)
4. Pricing y comparativa (viernes - cierre fuerte)

UTMs deben seguir patrón: ?utm_source=<plataforma>&utm_medium=organic&utm_campaign=<topic_v1>

Devuelve ÚNICAMENTE el JSON array, sin texto adicional.`

console.log(`📈 Growth Agent · ${today} · semana del ${monday}`)

const resp = await fetch('https://api.anthropic.com/v1/messages', {
  method: 'POST',
  headers: {
    'x-api-key': ANTHROPIC_API_KEY,
    'anthropic-version': '2023-06-01',
    'content-type': 'application/json',
  },
  body: JSON.stringify({
    model: 'claude-sonnet-4-5',
    max_tokens: 4096,
    system: SYSTEM_PROMPT,
    messages: [{ role: 'user', content: userPrompt }],
  }),
})

if (!resp.ok) {
  console.error('Claude failed:', await resp.text())
  process.exit(1)
}

const data = await resp.json()
const text = data?.content?.[0]?.text || ''
const jsonMatch = text.match(/\[[\s\S]*\]/)
if (!jsonMatch) {
  console.error('No JSON array in response:', text.slice(0, 300))
  process.exit(1)
}

let slideshows
try {
  slideshows = JSON.parse(jsonMatch[0])
} catch (e) {
  console.error('Invalid JSON:', e.message)
  process.exit(1)
}

let md = `# Cerebro · Growth Calendar — semana del ${monday}\n\n`
md += `_Generado: ${today}_\n\n`
md += `> 5 slideshows faceless para postear lun-vie. Mezcla TikTok/LinkedIn/Reels.\n`
md += `> Cada uno ya incluye hook, body slides con visuals y CTA con UTM.\n\n`
md += `---\n\n`

for (const s of slideshows) {
  md += `## ${s.day.toUpperCase()} — ${s.topic}\n\n`
  md += `**Para:** ${s.audience}\n`
  md += `**Formato sugerido:** ${s.format_priority}\n\n`
  md += `### Slide 1 — Hook\n`
  md += `> **${s.hook}**\n\n`
  if (Array.isArray(s.body)) {
    for (const b of s.body) {
      md += `### Slide ${b.slide}\n`
      md += `**Texto:** ${b.text}\n\n`
      md += `**Visual:** ${b.visual_hint}\n\n`
    }
  }
  md += `### Slide final — CTA\n`
  md += `**Texto:** ${s.cta.text}\n\n`
  md += `**URL:** ${s.cta.url}\n\n`
  md += `---\n\n`
}

md += `\n_Generated by Growth Agent · ${new Date().toISOString()}_\n`

const path = `docs/growth/${monday}-week.md`
mkdirSync(dirname(path), { recursive: true })
writeFileSync(path, md)
console.log(`✅ Growth calendar written to ${path}`)
