// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxvrpnjluuvoggxonfll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4dnJwbmpsdXV2b2dneG9uZmxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODAwNTMsImV4cCI6MjA2NDk1NjA1M30.hJxBEFBHXlL21vkxeMcs29MMbKUqNvIIecgJh3ZirvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);